# Generated by Django 2.1.8 on 2022-02-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='available_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_color', models.CharField(choices=[('green', 'green'), ('yellow', 'yellow'), ('blue', 'blue'), ('red', 'red'), ('black', 'black'), ('white', 'white')], max_length=20)),
                ('item_img', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_color', models.CharField(choices=[('green', 'green'), ('yellow', 'yellow'), ('blue', 'blue'), ('red', 'red'), ('black', 'black'), ('white', 'white')], max_length=12)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.CharField(max_length=30)),
                ('item_image', models.ImageField(upload_to='chart_image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('check_output', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usersname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='available_items',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Royalempire_app.usersname'),
        ),
    ]
