# Generated by Django 2.1.8 on 2022-02-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Royalempire_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_items',
            name='username',
        ),
    ]
