# Generated by Django 2.1.8 on 2022-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Royalempire_app', '0002_remove_available_items_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='item_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
