# Generated by Django 2.1.8 on 2022-02-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Royalempire_app', '0003_auto_20220220_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_items',
            name='item_img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
